### ISSUE TITLE
different types in operations

### ISSUE THREAD

**Issue by dixlorenz** [eatingtomatoes/pure_simd#4]
Is there a specific reason why unroll (and by extension most binary operations) expects 2 vectors of the same type? Obviously the size has to be the same, but I don't see why the type has to be the same.

**Comment by eatingtomatoes** [comment]
Is it too restrictive? I didn't realize that problem.

**Comment by eatingtomatoes** [comment]
We can relax the type requirements.

**Comment by dixlorenz** [comment]
That would be nice; I often have data streams of same lengths but wildly different types. 

Or for example your comparison operators already return bools; right now you can't really do anything with them. I could imagine:

vec_x = (vec_a >= vec_b) * vec_c; // zeroes those numbers of c where a < b

**Comment by eatingtomatoes** [comment]
Have you tried to test the performance of this library with real use cases? As I rarely used SIMD in my work, I found it hard for me to design performance test.

**Comment by dixlorenz** [comment]
lol, I just opened a new issue on performance on my machine :-)
