### ISSUE TITLE
some comments/issues

### ISSUE THREAD

**Issue by dixlorenz** [eatingtomatoes/pure_simd#6]
Hi,

first of all, I really like this library. I don't even know if I can/will use it, but the code is clean and I find the concept fascinating, it makes me think about stuff, that's always interesting :-) That said, a few comments:

a) ascend_from is weirdly named. I understand what it's supposed to mean, but the name doesn't convey that (to me). To be fair, I don't really have a better name, but the function is extremely similar to std::iota, maybe use that?

b) I think all the functions should be constexpr; I did a simple search/replace for inline, I can do a pull request if you want

c) I am working on Xcode 11.4.1 on an iMac Pro; I don't use Conan or google benchmarks, so I copied the routines and played around with them. No matter what flags/settings/variatons I try, automatic_tick and pure_simd_tick always take about the same time, intrinsic_tick is about 2.5 times faster. Also, to make sure the optimizer doesn't just throw away stuff, I had my code write screen[0] to cout; intrinsic_tick has a very different value. I know (I think) google benchmarks runs the loop based on time, so the number of iterations is different; in my code I loop the same number of times, the results should be identical. There is a bug somewhere in intrinsic_tick, I am still trying to find it but I haven't worked with intrinsics in ages...

**Comment by eatingtomatoes** [comment]
a) I will replace it with iota.
b) You can do that.
c) The vectorization process is divided into two parts, the second of which relies on the compiler's SLP vectorization pass. Different compilers have different slp vectorization capabilities, thus generate code of different performance. I have installed both clang-9 and gcc-7.5 on my machine. The former was senstive to the vector size, that is, bigger size leaded to better performance, while the latter always generated code of same performance.  
d) The automatic_tick/intrinsic_tick/pure_simd_tick are meaningless at present due to code simplification. You may have a look on the original shader code. But I think it's better to find and use some new cases.

**Comment by eatingtomatoes** [comment]
If you are using clang, you can get the ir by `clang -S -emit-llvm -O3 -march=native xxx.cpp`.

**Comment by dixlorenz** [comment]
c) I played around with optimization settings (-Ofast was best), vector extensions (AVX512 wins), vector sizes and tuple_n/array (no significant change); pure_simd and automatic were always about the same with intrinsics much faster. I am still digging here, I am not convinced yet that Xcode isn't setting something behind my back
d) I don't care about what the code actually does or if the results make sense; but if it gets a different result, it is doing something differently and a comparison of runtimes might be pointless

**Comment by dixlorenz** [comment]
d) -Ofast is changing the results (even in automatic!), -O3 is stable. I really don't like this, that would be the third extremely questionable thing I found about Xcode 11.4 clang...

c) I extracted everything to a minimal main.cpp, compiled manually with "clang -std=c++17 -stdlib=libc++ -lc++ -O3 -march=native main.cpp". Timings were consistent with what happened before, except now intrinsics is almost exactly 3 times faster than the other two. I even played around with -fno-vectorize/-fvectorize and -fno-unroll-loops/-funroll-loops. No idea If -O3 supersedes those flags anyway, the timings were still virtually the same. -O0 was slower, but those flags didn't change anything there either, neither in automatic nor pure_simd. At the moment I am at a loss what else to try; LLVM IR is... uh... I never ever seen that, so far it#s beyond me :-)

**Comment by eatingtomatoes** [comment]
That's sad. I will look into that later.

**Comment by dixlorenz** [comment]
OMFG... never mind, I am a complete *expletive* moron. While copy-pasting the timing code I didn't update the call to pure_simd_tick; it was still calling automatic_tick. No wonder they always got the same timing. Now pure_simd is about 30% faster than intrinsics :-) 

Next I'll try to profile using this over my use case...

**Comment by dixlorenz** [comment]
For benchmarking my use-case I added 100 arrays of 250.000 values. As I said, I have different types of values, so my adding function is templated on target and source, after taking away all the decoration, the loop simply looks like this:

`for (int i = 0; i < n; ++i)
            *target++ += theFactor * *source++;`

I always thought that a vectorizer/unroller should handle that easily and that in the end memory latency would be the limiting factor. My pure_simd-way looks like this:

`for (int i = 0; i < n; i += vector_size, t += vector_size, s += vector_size) {
            auto target = pure_simd::load_from<tvec>(t);
            auto source = pure_simd::load_from<svec>(s);
            pure_simd::store_to(target + (source * theScalarFactor), t);
         }`

My data always has enough padding at the end so I don't have to worry about the tail of the loop. At first I ran this with just doubles as values, pure_simd was a maybe a tiny bit faster; when I mixed in 100 integer-arrays, this version actually took 20-25% less time. When target is just a float, its takes less than 40% of the time. I am officially impressed! :-)

**Comment by eatingtomatoes** [comment]
Good news!

**Comment by eatingtomatoes** [comment]
This method does not seem to be suitable for handling small data types. I did a performance test on ascii code validation. Using pure simd, the best performance I can get was only slightly better than the one using 128-bit intrinsics.

**Comment by eatingtomatoes** [comment]
It could also be problems of my code. I am not good at simd programmming.

**Comment by dixlorenz** [comment]
If pure_simd is even in the ballpark of code using intrinsics (let alone "slightly better") I'd count that as a huge advantage. I never bothered writing my code using intrinsics because I'd have to handcraft each operation for each possible combination of types, that would be hundreds of routines. With pure_simd I can write generic code once for each operation and let the compiler worry about the types. it might not be optimal, but it's actually usable.

**Comment by dixlorenz** [comment]
I think pure_simd should have a transform:
```
   template<size_t VectorSize, typename F, typename T, typename S0, typename S1>
   void transform(const S0 *src0, const S1 *src1, T *dst, std::size_t n, F func) {
      unroll_loop<VectorSize>(0, n, [&](auto step, int i) {
         constexpr std::size_t vector_size = decltype(step)::value;

         using Source0Vec = pure_simd::array<S0, vector_size>;
         using Source1Vec = pure_simd::array<S1, vector_size>;

         store_to(func(load_from<Source0Vec>(src0 + i), load_from<Source1Vec>(src1 + i)), dst + i);
      });
   }
```

obviously also for just one source, maybe three or more sources? almost screams to have it variadic but I couldn't get that to compile :-)

Anyway, my code looks like this then:

```
        pure_simd::transform<8>(
            inTarget.get(), inSource.get(), inTarget.get(), inTarget.n(), [theFactor](auto a, auto b) {
               auto theScalarFactor = pure_simd::scalar<decltype(a)>(theFactor);
               return a + (b * theScalarFactor);
            });

```

inTarget and inSource are regular pointers to data... performance seems to be a bit better even and it's almost as straightforward to write as a normal transform. I am still amazed!

**Comment by dixlorenz** [comment]
This is getting ridiculous... Of course my datasource could also be a stream of bits; obviously that needs to be special-cased and that was always a huge nightmare. Enter pure_simd:

```
   namespace detail {
      template <typename V, typename T, size_t... Is>
      constexpr V splat_bits_impl(T bits, std::index_sequence<Is...>)
      {
         return { static_cast<typename V::value_type>(((bits >> Is) & 0x01))... };
      }
   } // namespace detail


   template<typename V, typename T, typename = must_be_vector<V>>
   constexpr V splat_bits(T bits) {
      static_assert((sizeof(T) * CHAR_BIT) >= sizeof(typename V::value_type));
      return detail::splat_bits_impl<V>(bits, index_sequence_of<V> {});
   }

```

splat_bits sets the elements of the vector to the corresponding bits. It could also be called scatter or spread... anyway, the loop:

```
constexpr std::size_t vector_size = 8;

         using TargetVec       = pure_simd::array<TargetType, vector_size>;
         const auto theSummand = pure_simd::scalar<TargetVec>(static_cast<TargetType>(factor));

         const std::uint8_t *s = inSource.get();
         auto          t = inTarget.get();

         for (int i = 0; i < inTarget.n(); i += vector_size, t += vector_size) {
            auto target  = pure_simd::load_from<TargetVec>(t);
            auto theBits = pure_simd::splat_bits<TargetVec>(*s++);
            pure_simd::store_to(target + (theBits * theSummand), t);
         }

```

This is the most readable I have ever seen this part of my code. And my test-case is now almost 4 (!) times as fast.

**Comment by dixlorenz** [comment]
It would need to be called scatter_bits, the antonym for scatter is gather:

```
   namespace detail {
      template <typename V, typename T, size_t... Is>
      constexpr V scatter_bits_impl(T bits, std::index_sequence<Is...>)
      {
         return { static_cast<typename V::value_type>(((bits >> Is) & 0x01))... };
      }

   } // namespace detail


   template<typename V, typename T, typename = must_be_vector<V>>
   constexpr V scatter_bits(T bits) {
      return detail::scatter_bits_impl<V>(bits, index_sequence_of<V> {});
   }

   namespace detail {
      template <typename T, size_t Idx, typename V>
      constexpr T gather_bit(V x) { return static_cast<T>((x[Idx] != 0) << Idx); }

      template <typename T, typename V, size_t... Is>
      constexpr T gather_bits_impl(V x, std::index_sequence<Is...>)
      {
         return (gather_bit<T, Is>(x) | ...) ;
      }
   } // namespace detail


   template<typename T, typename V, typename = must_be_vector<V>>
   constexpr T gather_bits(V x) {
      static_assert((sizeof(T) * CHAR_BIT) >= sizeof(typename V::value_type));
      return detail::gather_bits_impl<T>(x, index_sequence_of<V> {});
   }

```
gather_bits does the opposite of scatter_bits. I have no benchmark for it but it feels right.

Anyway, I'll play a lot with this over the next few days (if not weeks)... are you interested in routines like these that I write? I am hesitant to just use pull requests since I don't know if you want these in pure_simd and writing new code will automatically get formatted using my clang-format settings; I would try to match your code-style, but I'd be sure to miss some tabs etc... 

Let me know and thanks for this awesome library!

**Comment by eatingtomatoes** [comment]
1) I am glad to add new functions. 
2) There is a `.clang-format` in the root directory of source code, so the style will be consistent if you run clang-format.
3) Could you share the code of your performance test? Currently the only test on that meaningless shader is not satisfactory.

**Comment by eatingtomatoes** [comment]
Will you use std::tuple? It seems to be useless and causes trouble. I am planning to drop it.

**Comment by dixlorenz** [comment]
I can't think of any reason to use tuples over arrays here, I certainly won't use them.
I am using Xcode which doesn't actually support clang-format; I have to use a plug-in which cannot parse the filesystem, so the path to .clang-format is hardcoded to mine :-(
My benchmarks are deep inside tons of other code; but I should be able to write up something meaningful; you'd have to wrap it in some kind of benchmark-framework though.

**Comment by dixlorenz** [comment]
I see you've been busy :-) Currently I am cooking up some benchmarking code and I am starting to wonder something. Why exactly do unroll_loop (and transform) expect the functor to use vectors? it means that client code needs to be templated, because the size of the vector cannot be known. This leads to longer compilation times and code size. On the other hand, most of the stuff in the functor would probably use operations on the vectors, in the end calling unroll on them. If we hoist the call to unroll into unroll_loop, transform (and accumulate, inner_product which I am currently working on) the client code would operate on the scalar values, the migration from std::transform to pure_simd::transform would be trivial, the functor can use operations that are not available for vectors etc... 
If the Vector is more tuple-like (RGBA values, x/y/z coordinates...) one needs the vector of course; but then one can simple use the standard algorithms.

**Comment by eatingtomatoes** [comment]
Yeah, I am a little busy with work :-).
I am not able to understand you words very well. Maybe an example will help.

**Comment by eatingtomatoes** [comment]
I really appreciate your enthusiastic help with this library. It's hard for me to develop it by myself.

**Comment by dixlorenz** [comment]
(This is all typed/edited in here, probably has typos)
Assume I have a function "popcount" that counts the bits in an integer. What if I want to count all the bits in a vector of ints?

```
std::accumulate(
         source, source + N, 0, [](int curr, int val) { return curr + popcount(val); });
```

if pure_simd::accumulate expects a functor to use vectors:

```
template<size_t VectorSize, typename T, typename S, typename F>
   auto accumulate(const S *src, std::size_t n, T init, F func) {
      assert((n % VectorSize) == 0);

      using Source = array<S, VectorSize>;
      using Target = array<T, VectorSize>;

      auto sum = scalar<Target>(init);
      for (std::size_t i = 0; i < n; i+= VectorSize, src += VectorSize)
         sum = func(sum, load_from<Source>(src));

      return sum;
}

```
 the call would have to be something like this:

```
pure_simd::accumulate<8>(
         source, source + N, 0, [](auto curr, auto vals) { return curr + pure_simd::unroll(vals, [](auto byte) { return popcount(byte); }); });

```
But if we put the unroll into pure_simd::accumulate: 

```
   template<size_t VectorSize, typename T, typename S, typename F>
   auto accumulate(const S *src, std::size_t n, T init, F func) {
      assert((n % VectorSize) == 0);

      using Source = array<S, VectorSize>;
      using Target = array<T, VectorSize>;

      auto sum = scalar<Target>(init);
      for (std::size_t i = 0; i < n; i+= VectorSize, src += VectorSize)
         sum = unroll(sum, load_from<Source>(src), func);

      return sum;
   }

```

the call becomes simply:

```
pure_simd::accumulate<8>(
         source, source + N, 0, [](int curr, int val) { return curr + popcount(val); });

```

Much easier to write, actually the functor is exactly the same as for std::accumulate and I *think* the performance should be the same. Note that I ignored the tail-part; but because of that problem the first use case needs to have auto as parameters, the second one can be an untemplated function

**Comment by eatingtomatoes** [comment]
I see. It's more friendly to users. I'll try to implement new functions in the second style.

**Comment by dixlorenz** [comment]
I am happy to help. I've been working on these routines for almost 30 years (!), seeing these kinds of speedup with code that is portable and just as easy to write (sometimes even easier) is absolutely fascinating to me :-)

**Comment by dixlorenz** [comment]
for transform your comment says "Both `src` and `dst` should be a random access iterator". transform uses load_from, that will only work on contiguous memory. That's also why I gave the function "n" instead of and end-iterator. The algorithms here make only sense for contiguous memory (I think).

**Comment by dixlorenz** [comment]
This is what I got now. One new operation, sum; sums up all the elements of a vector. 3 algorithms, transform, accumulate and inner_product. I switched around the arguments for transform to be as closely as possible to std::transform. 

For all 3 algorithms I simply loop over the remainder; I would argue that n should be big enough that this doesn't matter. It makes the code a lot easier and saves the compiler from instantiating even more templates.

accumulate and inner_product actually return a vector; it is easy enough to sum them up (hence the new operation) and the right hand side of the adding_functor is expecting the type of the multiplication, not the type of the adding_functor. 

I added simple tests for accumulate and inner_product. Also some benchmarks. Looks very artificial, in my actual code the data vectors would be stuffed inside a std::variant, I left those parts out here. I don't have/use/ google benchmark or testing, I hope it should be easy to adapt the code; DLCL::Timer::Measure is my benchmarking call.

[pure_simd_ext.txt](https://github.com/eatingtomatoes/pure_simd/files/4638220/pure_simd_ext.txt)

**Comment by eatingtomatoes** [comment]
OK, I will merge it into the master.

**Comment by dixlorenz** [comment]
Sweet, thanks :-) I have another thought:

```
   constexpr int register_size_bits = 512;
   constexpr int register_size = register_size_bits / CHAR_BIT;

   template<typename T, typename... Ts>
   constexpr int streaming_vectorsize() { return register_size / std::max({0UL, sizeof(T), (sizeof(Ts))...}); }

```
Are you aware of any function to find out how large the SIMD-Registers are? A function like streaming_vectorsize could calculate the (probably) optimal vectorsize for transform etc... making it a nice default.

**Comment by eatingtomatoes** [comment]
I'm afraid not, but I'll search for it later.

**Comment by eatingtomatoes** [comment]
Hi, I'd like to you share with you my recent thoughts on this library.

I did some benchmarks on my machine, including calculating the product of matrix and  vector, ascii validation and zipping two sequences into one with simple arithmetic. Performance was improved using  vectors of some specific sizes. But the improvement was not as impressive as that on shader case, which even defeated intrinsics. (Also, for the benchmark on `sum`, I got the same best improvement using vectors of size 1 and size 16 on my machine. That's ridiculous!)

I am wondering why I cannot achieve that acclerating effect anymore. Currently, I guess that the library does not help much with logically simple code, as the compiler already optimized them very well. The acclerating effect observed in your benchmarks mainly came from loop unrolling instead of vectorization.

I think the shader case deservs a in-depth analysis. In fact, if you look at the LLVM IR or assembly code generated by clang, you will find that the automatic_tick was indeed autovectorized by the compiler. But it was done in a wrong direction. The compiler was trying to vectorize the inner most loops, containing a lot of dependencies between statements, thus generated bad code. However, the pure_simd_tick was vectorizing the second one, which exhibited great parallelism. The LLVM IR showed that the loop was vectorized perfectly. 

So, I am thinking about the position of this library in optimization. Maybe it's better to use pure-simd to guide the compiler to correct direction of optimization.

**Comment by eatingtomatoes** [comment]
I found some materials in theory about techniques involved in this library. You may take a look at this paper "Outer-loop vectorization: revisited for short SIMD architectures", especially section 2.3.4 (https://dl.acm.org/doi/10.1145/1454115.1454119). It's free to access at the moment.

In fact, the pure_simd_shader vectorized the outer loop, which has greater parallelsim than the innermost, thus got better performance.

Therefore, I tend to think that the library is more suitable for guiding compilers to do right optimization.

**Comment by dixlorenz** [comment]
That's what I thought the library was for, as you wrote in the introduction: "It just unrolls loops introduced by various vector operations at compile time and leaves the rest work to compilers". In a way, it is "just" a fancy unroller where the data for an unrolled loop is stored in a vector which could presumably also give the vectorizer a better chance of optimizing.

**Comment by eatingtomatoes** [comment]
After looking at the IR that clang spit out, I found the compiler did not vectorize the new shader example at all, which quite surprised me. I didn't expect simple code expansion to make such a big difference.

**Comment by eatingtomatoes** [comment]
It deserves a more in-depth analysis.
