### ISSUE TITLE
Doesn't seem to work on a simple use case

### ISSUE THREAD

**Issue by Steve132** [eatingtomatoes/pure_simd#9]
So, I have this fairly simple use case:  Basically, I am looking on a scan-line for 'segments' e.g. basically looking through an array of chars such as `0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 0 0 0 0 0 `, then trying to output each contiguous segment as a begin/end index, like the above example would become two segments `{{6,16},{21,24}}`.

However, I strongly suspect that in my data these strings will be VERY long and segments of zeros will be hundreds of elements long.  So I wanted to vectorize it.  The basic strategy for vectorization is just going to be if the loaded data is all zero then skip ahead, if it's all ones then grow the current segment and skip ahead.     if neither case is true then for this block drop down to a standard element-by-element processing (which should only happen on blocks that cover a boundary).

This is a pretty simple case that would be easy for intrinsics, but I wanted to try pure_simd.  Here is my code.

	struct segment_t{
		uint32_t start,finish,id,row;
		segment_t(uint32_t s=0,uint32_t f=0):start(s),finish(f),id(0),row(0)
		{}
	};

	void find_segments_in_row_vec(const uint8_t* row_ptr,size_t cols,std::vector<segment_t>& vec,size_t ms)
	{
		bool previous=false;
		segment_t cur_segment;
		pure_simd::unroll_loop<pure_simd::register_size>(
		    0,cols,[&](auto step,uint32_t col)
		    {
		        constexpr std::size_t vector_size = decltype(step)::value; 
		        using ucvec = pure_simd::vector<uint8_t, vector_size>;
		        ucvec vals=pure_simd::load_from<ucvec>(row_ptr+col); //Load the block
		        unsigned int numvals=pure_simd::sum(vals,0);	//count how many there are
		        if(!previous && numvals==0)						//if we're not in a segment and this is a block of zeros, skip to the next block
		        {
		            return;
		        }
		        else if(previous && numvals==vector_size)		//if we are in a segment and this is a block of ones, add the whole block to the segment and skip to the next block
		        {
		            cur_segment.finish+=vector_size;
		            return;
		        }
		        for(int i=0;i<vector_size;i++)					//otherwise process the block sequentially.
		        {
		            bool current=vals[i];
		            if(current==previous)						//if we're in the middle of a pattern
		            {
		                cur_segment.finish+=current;			//extend the current block (zeros will drop the block)
		            }
		            else if(current)							//if we're starting a block, drop the current and start a new block
		            {
		                cur_segment.start=col;
		                cur_segment.finish=col+1;
		            }
		            else if(!current)							//if we're ending a block, append it to the list.
		            {
		                vec.push_back(cur_segment);
						cur_segment=segment_t{};
		            }
		        }
		    }
		);
		if((cur_segment.finish-cur_segment.start)!=0) {		//if the last block was a segment, append it.
		    vec.push_back(cur_segment);
		}
	}
	
But looking at the output with g++10 shows no vectorization with `-O3 -mnative`.  I've also attached the output of `-fopt-info-missed=missed.all` Here. 
[missed.all.log](https://github.com/eatingtomatoes/pure_simd/files/7272368/missed.all.log)

**Comment by eatingtomatoes** [comment]
I tried to optimize your code but failed. 

The problem is that, in order to determine whether a vector is full of ones or zeros, a reduction operation is needed, which will serialize the execution and erase the benefits of vectorization. Thus the compiler refused to vectorize the code.

The reduction operation seems inevitable, so I'm curious if you can get performance boost by using intrinsics.

**Comment by Steve132** [comment]
The reduction is a simple horizontal sum, which  1) seems like it should be supported in pure_simd (isn't that what psd::max and psd::sum do? if not, why even have them exposed as part of the api?)  
2) it's _mm_sad_epu8 for a single instruction in sse2 or a sequence of 3 vpaddlq in NEON.  

I could implement the same thing probably by using gather_bits and checking against ~0 I guess.   I don't think that has a corresponding NEON intrinsic but you can do it in a single instruction across 64 lanes with vpcmpub on AVX512.

If it can't do horizontal sums or any kind of reductions without breaking parallelism in pure_simd, then I feel like you should actually *delete* the functions `gather_bits`,`accumulate`,`sum` and `inner_product` entirely from your public API, because those functions make it seem like they are expected to work when in reality anyone who uses them will apparently break the auto-vectorizer.

EDIT: I tried it with `gather_bits` as well and yes it seems `gather_bits` does not vectorize either.    

My suggestion is that pure_simd should only provide the operations which do not destroy vectorization in it's public api, or perhaps tag them with a warning in some way that they cannot be used.

**Comment by eatingtomatoes** [comment]
In this test case (https://godbolt.org/z/PxT1x339G), the `sum` was vectorized by clang but not by gcc.

**Comment by eatingtomatoes** [comment]
In this test case (https://godbolt.org/z/6PzzKzMx4), the `sum` was vectorized by clang but not by gcc.

**Comment by eatingtomatoes** [comment]
I rewrote your code and pasted it here (https://godbolt.org/z/zhK7vs4hz).

The modifications include avoiding the use of unroll_loop, which can make the generated code very cluttered, and specifying the size of the vector to 16. 

At lines 34 and 37 of the code generated by clang, you can see two vpsadbw(i.e. _mm256_sad_epu8) instructions. Sadly, they were not found in the code output by gcc.

**Comment by Steve132** [comment]
Yeah you're right gcc doesn't vectorize it but clang does.  That's pretty cool!  Do you know if there's a specific pattern that gcc isnt' recognizing?

Also, when I change it to my actual code, clang still seems to vectorize it but it seems to skip vectorizing the load and generating.   As in it uses a sequence of 16-64 mov 4 byte movs and loads them individually into the register.  

Both cases also skip the 512 bit wide operands and do a lot more than is necessary.  Still it's good to know that `psd::sum` works a little bit on clang!  Too bad about gcc.

I tested `gather_bits` and it doesn't seem to work either.  I'd expect it to generate   In fact, on clang the code it creates is clearly bugged: https://godbolt.org/z/xMT3x6rv6

**Comment by eatingtomatoes** [comment]
Sorry, I know very little about the vectorizer of gcc, so I cannot say which pattern gcc is able to recognize.

The reason why clang generated bad code, I guess, is that the vectorizer of clang does not yet support AVX512 (completely). That's what I found when I was studying the implementation of clang some time ago. I‘m not sure if it is changed now.

**Comment by Steve132** [comment]
To be clear I don't just mean clang creates bad code.  I mean it looks to me like `gather_bits` is producing broken code.  It looks like it's generating a no-op for the gather operation.

**Comment by Steve132** [comment]
> I rewrote your code and pasted it here (https://godbolt.org/z/zhK7vs4hz).

Hmm  that's interesting.   thank you, that gives me a halfway decent starting point at least.  I still think `gather_bits` not working is a big problem.  But yeah this gets me started.

**Comment by eatingtomatoes** [comment]
Sorry, it's a bug in the pure_simd. I have fixed it and now clang generates correct(but bad) code.
